language: perl
perl:
 - "5.22"
 - "5.24"
 - "5.26"
 - "5.28"
 - "5.30"
notifications:
    email:
        on_success: "change"
        on_failure: "always"
env: AUTHOR_TESTING=1 RELEASE_TESTING=1 AUTOMATED_TESTING=1 EXTENDED_TESTING=1
sudo: false
branches:
    only:
        - master
        - dev
